packages:
  # 存放组件库和其他工具库
  - "packages/*"
  # 存放组件测试的代码
  - "example"
  # 存放文档
  - "docs"

catalog:
  "@vitejs/plugin-vue": "^5.1.4"
  "@vueuse/core": ^11.2.0
  "@vue/shared": ^3.5.12
  "@ctrl/tinycolor": ^4.1.0
  "@vue/runtime-dom": ^3.5.12
  "@vitejs/plugin-vue-jsx": ^4.0.1
  "@iconify/vue": ^4.1.2
  echarts: ^5.5.1
  typescript: ^5.4.2
  vite: ^5.4.10
  vite-plugin-vue-setup-extend: ^0.4.0
  vue: ^3.5.12
  vue-tsc: ^1.8.5
  less: ^4.2.0
  clsx: ^2.1.1
  tailwind-merge: ^2.5.4
  defu: ^6.1.4
  nprogress: ^0.2.0
  lodash.clonedeep: ^4.5.0
  vue-router: ^4.4.5
  vite-plugin-copy: 0.1.6
  theme-colors: ^0.1.0
  fs-extra: ^11.1.0
  vite-plugin-dts: ^4.4.0
  ant-design-vue: ^4.2.5
  vitepress: ^1.5.0
