// 系统类图标
const systemIcons = [
  'mdi:cog',
  'mdi:settings',
  'mdi:tools',
  'mdi:wrench',
  'mdi:account-cog',
  'mdi:database-cog',
  'mdi:cog-refresh',
  'mdi:cog-sync',
  'mdi:application-cog',
  'mdi:cog-outline',
  'mdi:cog-transfer',
  'mdi:cog-stop',
  'mdi:cog-play',
  'mdi:cog-pause',
  'mdi:server',
  'mdi:database',
];

// 导航类图标
const navigationIcons = [
  'mdi:home',
  'mdi:view-dashboard',
  'mdi:menu',
  'mdi:folder',
  'mdi:folder-open',
  'mdi:file',
  'mdi:file-document',
  'mdi:file-chart',
  'mdi:chart-bar',
  'mdi:chart-line',
  'mdi:chart-pie',
  'mdi:chart-timeline',
  'mdi:compass',
  'mdi:map',
  'mdi:arrow-left',
  'mdi:arrow-right',
  'mdi:arrow-up',
  'mdi:arrow-down',
  'mdi:chevron-left',
  'mdi:chevron-right',
  'mdi:menu-down',
  'mdi:menu-up',
  'mdi:sitemap',
  'mdi:view-grid',
  'mdi:view-list',
];

// 用户类图标
const userIcons = [
  'mdi:account',
  'mdi:account-group',
  'mdi:account-circle',
  'mdi:account-key',
  'mdi:account-multiple',
  'mdi:account-supervisor',
  'mdi:account-tie',
  'mdi:account-star',
  'mdi:account-plus',
  'mdi:account-minus',
  'mdi:account-remove',
  'mdi:account-edit',
  'mdi:account-check',
  'mdi:account-alert',
  'mdi:account-box',
  'mdi:account-details',
  'mdi:account-settings',
  'mdi:account-search',
  'mdi:account-network',
  'mdi:account-lock',
];

// 通信类图标
const communicationIcons = [
  'mdi:email',
  'mdi:message',
  'mdi:chat',
  'mdi:phone',
  'mdi:video',
  'mdi:bell',
  'mdi:bell-ring',
  'mdi:comment',
  'mdi:email-outline',
  'mdi:email-send',
  'mdi:email-receive',
  'mdi:message-text',
  'mdi:message-image',
  'mdi:message-video',
  'mdi:message-processing',
  'mdi:phone-incoming',
  'mdi:phone-outgoing',
  'mdi:phone-missed',
  'mdi:chat-processing',
  'mdi:forum',
];

// 操作类图标
const actionIcons = [
  'mdi:plus',
  'mdi:minus',
  'mdi:close',
  'mdi:check',
  'mdi:refresh',
  'mdi:sync',
  'mdi:delete',
  'mdi:pencil',
  'mdi:magnify',
  'mdi:filter',
  'mdi:plus-circle',
  'mdi:minus-circle',
  'mdi:close-circle',
  'mdi:check-circle',
  'mdi:refresh-circle',
  'mdi:sync-circle',
  'mdi:delete-circle',
  'mdi:pencil-circle',
  'mdi:magnify-plus',
  'mdi:magnify-minus',
  'mdi:filter-variant',
  'mdi:sort-ascending',
  'mdi:sort-descending',
  'mdi:undo',
  'mdi:redo',
];

// 状态类图标
const statusIcons = [
  'mdi:alert',
  'mdi:information',
  'mdi:check-circle',
  'mdi:alert-circle',
  'mdi:shield',
  'mdi:lock',
  'mdi:lock-open',
  'mdi:eye',
  'mdi:eye-off',
  'mdi:alert-octagon',
  'mdi:alert-box',
  'mdi:progress-check',
  'mdi:progress-clock',
  'mdi:progress-close',
  'mdi:shield-check',
  'mdi:shield-alert',
  'mdi:lock-check',
  'mdi:lock-alert',
  'mdi:check-decagram',
  'mdi:close-octagon',
];

// 媒体类图标
const mediaIcons = [
  'mdi:image',
  'mdi:camera',
  'mdi:video',
  'mdi:music',
  'mdi:play',
  'mdi:pause',
  'mdi:stop',
  'mdi:volume-high',
  'mdi:image-multiple',
  'mdi:image-plus',
  'mdi:image-edit',
  'mdi:camera-plus',
  'mdi:video-plus',
  'mdi:playlist-music',
  'mdi:playlist-plus',
  'mdi:volume-medium',
  'mdi:volume-low',
  'mdi:volume-off',
  'mdi:movie',
  'mdi:movie-open',
];

// 其他常用图标
const otherIcons = [
  'mdi:star',
  'mdi:heart',
  'mdi:thumb-up',
  'mdi:bookmark',
  'mdi:calendar',
  'mdi:clock',
  'mdi:map-marker',
  'mdi:link',
  'mdi:cloud',
  'mdi:download',
  'mdi:upload',
  'mdi:printer',
  'mdi:star-outline',
  'mdi:heart-outline',
  'mdi:thumb-up-outline',
  'mdi:bookmark-outline',
  'mdi:calendar-blank',
  'mdi:clock-outline',
  'mdi:map-marker-outline',
  'mdi:link-variant',
  'mdi:cloud-outline',
  'mdi:download-outline',
  'mdi:upload-outline',
  'mdi:printer-outline',
  'mdi:tag',
  'mdi:tag-outline',
  'mdi:gift',
  'mdi:gift-outline',
  'mdi:currency-usd',
  'mdi:currency-eur',
];

// 导出所有图标
export const icons = [
  ...systemIcons,
  ...navigationIcons,
  ...userIcons,
  ...communicationIcons,
  ...actionIcons,
  ...statusIcons,
  ...mediaIcons,
  ...otherIcons,
];

// 导出图标分类
export const iconCategories = {
  system: systemIcons,
  navigation: navigationIcons,
  user: userIcons,
  communication: communicationIcons,
  action: actionIcons,
  status: statusIcons,
  media: mediaIcons,
  other: otherIcons,
};
